#Import dependecies

In [40]:
import pandas as pd
import numpy as np
from sklearn import linear_model

##Load the dataset

In [41]:
df = pd.read_csv("Cars_price.csv")

In [42]:
print(df.columns)

Index(['cylinders', ' milage', ' year', ' price'], dtype='str')


#Preprocessing

In [43]:
df.columns = df.columns.str.strip()
print(df.columns)

Index(['cylinders', 'milage', 'year', 'price'], dtype='str')


##Lets add a row

In [44]:
df.loc[5]=[3, 50000, None, 2100000]

In [45]:
df

,cylinders,milage,year,price
0,3.0,30000.0,2024.0,2500000.0
1,4.0,25000.0,2022.0,3100000.0
2,4.0,50000.0,2020.0,2400000.0
3,6.0,30000.0,2023.0,5000000.0
4,8.0,25000.0,2022.0,8000000.0
5,3.0,50000.0,NaN,2100000.0


In [46]:
df.describe()

,cylinders,milage,year,price
count,6.000000,6.000000,5.00000,6.000000e+00
mean,4.666667,35000.000000,2022.20000,3.850000e+06
std,1.966384,11832.159566,1.48324,2.284513e+06
min,3.000000,25000.000000,2020.00000,2.100000e+06
25%,3.250000,26250.000000,2022.00000,2.425000e+06
50%,4.000000,30000.000000,2022.00000,2.800000e+06
75%,5.500000,45000.000000,2023.00000,4.525000e+06
max,8.000000,50000.000000,2024.00000,8.000000e+06


##Handle missing data

In [47]:
mean_year = int(df['year'].mean())
df['year'] = df['year'].fillna(float(mean_year))
df

,cylinders,milage,year,price
0,3.0,30000.0,2024.0,2500000.0
1,4.0,25000.0,2022.0,3100000.0
2,4.0,50000.0,2020.0,2400000.0
3,6.0,30000.0,2023.0,5000000.0
4,8.0,25000.0,2022.0,8000000.0
5,3.0,50000.0,2022.0,2100000.0


#Train the Model

In [48]:
reg = linear_model.LinearRegression()
reg.fit(df[['cylinders', 'milage', 'year']], df.price)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](3,)","[1127900.04, -5.56, 209623.27]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](3,)","['cylinders','milage','year']"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,-4.251e+08
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,3
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(3)


#Model Parameters

In [49]:
reg.coef_

array([ 1.12790004e+06, -5.56135770e+00,  2.09623275e+05])

In [50]:
reg.intercept_

np.float64(-425112085.0428948)

In [51]:
reg.predict([[4, 30000, 2021]])

C:\Users\H P\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([2881312.94293171])

In [52]:
hiring = pd.read_csv("hiring.csv")
hiring

,experience,test_score,interview_score,salary
0,NaN,8.0,9,50000
1,NaN,8.0,6,45000
2,5.0,6.0,7,60000
3,2.0,10.0,10,65000
4,7.0,9.0,6,70000
5,3.0,7.0,10,62000
6,10.0,NaN,7,72000
7,11.0,7.0,8,80000


In [53]:
hiring['experience'].fillna(0, inplace=True)

C:\Users\H P\AppData\Local\Temp\ipykernel_14020\3713478144.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  hiring['experience'].fillna(0, inplace=True)


0     0.0
1     0.0
2     5.0
3     2.0
4     7.0
5     3.0
6    10.0
7    11.0
Name: experience, dtype: float64

In [54]:
hiring

,experience,test_score,interview_score,salary
0,NaN,8.0,9,50000
1,NaN,8.0,6,45000
2,5.0,6.0,7,60000
3,2.0,10.0,10,65000
4,7.0,9.0,6,70000
5,3.0,7.0,10,62000
6,10.0,NaN,7,72000
7,11.0,7.0,8,80000


In [55]:
import math

mean_test = hiring['test_score'].mean()
hiring['test_score'] = hiring.test_score.fillna(math.floor(mean_test))
hiring

,experience,test_score,interview_score,salary
0,NaN,8.0,9,50000
1,NaN,8.0,6,45000
2,5.0,6.0,7,60000
3,2.0,10.0,10,65000
4,7.0,9.0,6,70000
5,3.0,7.0,10,62000
6,10.0,7.0,7,72000
7,11.0,7.0,8,80000


In [57]:
reg_hiring = linear_model.LinearRegression()
reg.fit(hiring[['experience', 'test_score','interview_score']], hiring.salary)

ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [58]:
hiring = hiring.fillna(0)
reg_hiring = linear_model.LinearRegression().fit(hiring[['experience','test_score','interview_score']], hiring.salary)

In [59]:
reg.predict([[2, 9, 6],[12, 10, 10]])

C:\Users\H P\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-4.21598595e+08, -4.09481107e+08])

In [60]:
import pickle

In [61]:
with open('car_pred_model','wb')as file:
    pickle.dump(reg, file)

In [62]:
with open('car_pred_model','rb') as file:
    mp = pickle.load(file)

mp.predict([[2,9,6]])

C:\Users\H P\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-4.21598595e+08])

In [63]:
cars = pd.read_csv('carprices.csv')

In [64]:
cars

,Car Model,Mileage,Sell Price($),Age(yrs)
0,BMW X5,69000,18000,6
1,BMW X5,35000,34000,3
2,BMW X5,57000,26100,5
3,BMW X5,22500,40000,2
4,BMW X5,46000,31500,4
5,Audi A5,59000,29400,5
6,Audi A5,52000,32000,5
7,Audi A5,72000,19300,6
8,Audi A5,91000,12000,8
9,Mercedez Benz C class,67000,22000,6


In [65]:
cars.columns = ['Car_Model', 'Milage', 'Sell_Price', 'Age']
cars

,Car_Model,Milage,Sell_Price,Age
0,BMW X5,69000,18000,6
1,BMW X5,35000,34000,3
2,BMW X5,57000,26100,5
3,BMW X5,22500,40000,2
4,BMW X5,46000,31500,4
5,Audi A5,59000,29400,5
6,Audi A5,52000,32000,5
7,Audi A5,72000,19300,6
8,Audi A5,91000,12000,8
9,Mercedez Benz C class,67000,22000,6


##One‑hot encode the Car_Model column to convert into numerical data for traininng the model.

The model can only be trained on numerical data

In [66]:
dummies = pd.get_dummies(cars.Car_Model)
dummies

,Audi A5,BMW X5,Mercedez Benz C class
0,False,True,False
1,False,True,False
2,False,True,False
3,False,True,False
4,False,True,False
5,True,False,False
6,True,False,False
7,True,False,False
8,True,False,False
9,False,False,True


In [67]:
dum_cars = pd.concat([cars,dummies], axis = 'columns')
dum_cars

,Car_Model,Milage,Sell_Price,Age,Audi A5,BMW X5,Mercedez Benz C class
0,BMW X5,69000,18000,6,False,True,False
1,BMW X5,35000,34000,3,False,True,False
2,BMW X5,57000,26100,5,False,True,False
3,BMW X5,22500,40000,2,False,True,False
4,BMW X5,46000,31500,4,False,True,False
5,Audi A5,59000,29400,5,True,False,False
6,Audi A5,52000,32000,5,True,False,False
7,Audi A5,72000,19300,6,True,False,False
8,Audi A5,91000,12000,8,True,False,False
9,Mercedez Benz C class,67000,22000,6,False,False,True


In [68]:
dum_cars.rename(columns={'Mercedez Benz C class': 'Mercedes_C_class'}, inplace=True)

In [69]:
dum_cars

,Car_Model,Milage,Sell_Price,Age,Audi A5,BMW X5,Mercedes_C_class
0,BMW X5,69000,18000,6,False,True,False
1,BMW X5,35000,34000,3,False,True,False
2,BMW X5,57000,26100,5,False,True,False
3,BMW X5,22500,40000,2,False,True,False
4,BMW X5,46000,31500,4,False,True,False
5,Audi A5,59000,29400,5,True,False,False
6,Audi A5,52000,32000,5,True,False,False
7,Audi A5,72000,19300,6,True,False,False
8,Audi A5,91000,12000,8,True,False,False
9,Mercedez Benz C class,67000,22000,6,False,False,True


##Drop the contextual column

In [70]:
dum_cars = dum_cars.drop('Car_Model', axis='columns')

In [71]:
l_model = linear_model.LinearRegression()

In [79]:
y = cars.Sell_Price
print(y)
X = dum_cars.drop('Sell_Price', axis = 'columns')
X


0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell_Price, dtype: int64


,Milage,Age,Audi A5,BMW X5,Mercedes_C_class
0,69000,6,False,True,False
1,35000,3,False,True,False
2,57000,5,False,True,False
3,22500,2,False,True,False
4,46000,4,False,True,False
5,59000,5,True,False,False
6,52000,5,True,False,False
7,72000,6,True,False,False
8,91000,8,True,False,False
9,67000,6,False,False,True


#Now train this data on linear regression and predict price for 45000 milage,4 years old Mercedes C class and 86000 milage, 7 years old Audi A5

In [77]:
#Code here

In [78]:
df.columns

Index(['cylinders', 'milage', 'year', 'price'], dtype='str')

In [81]:
reg = linear_model.LinearRegression()
reg.fit(df[['cylinders','milage','year']], df.price)

reg.predict([[4,45000,2021]])

C:\Users\H P\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([2797892.57739645])

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df[['cylinders','milage','year']], df.price)

reg.predict([[7,86000,202]])